[versions]
kotlin-version = "2.2.21"
apache-avro-version = "1.12.1"

[libraries]
kotlin-jvm = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-version" }
avro-tools = { module = "org.apache.avro:avro-tools", version.ref = "apache-avro-version" }